const cards = [
  [
    {
      word: 'Action',
      image: './assets/images/hug.jpg',
      audioSrc: './assets/audio/Action.mp3',
    },
    {
      word: 'Colors',
      image: './assets/images/green.jpg',
      audioSrc: './assets/audio/Colors.mp3',
    },
    {
      word: 'Animal',
      image: './assets/images/rabbit.jpg',
      audioSrc: './assets/audio/Animal.mp3',
    },
    {
      word: 'Vegetables',
      image: './assets/images/tomato.jpg',
      audioSrc: './assets/audio/Vegetables.mp3',
    },
    {
      word: 'Clothes',
      image: './assets/images/blouse.jpg',
      audioSrc: './assets/audio/Clothes.mp3',
    },
    {
      word: 'Emotions',
      image: './assets/images/cry.jpg',
      audioSrc: './assets/audio/Emotions.mp3',
    },
    {
      word: 'Food',
      image: './assets/images/eggs.jpg',
      audioSrc: './assets/audio/Food.mp3',
    },
    {
      word: 'Fruits',
      image: './assets/images/mango.jpg',
      audioSrc: './assets/audio/Fruits.mp3',
    },
  ],
  [
    {
      word: 'cry',
      translation: 'плакать',
      image: './assets/images/cry.jpg',
      audioSrc: './assets/audio/cry.mp3',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: './assets/images/dance.jpg',
      audioSrc: './assets/audio/dance.mp3',
    },
    {
      word: 'dive',
      translation: 'нырять',
      image: './assets/images/dive.jpg',
      audioSrc: './assets/audio/dive.mp3',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: './assets/images/draw.jpg',
      audioSrc: './assets/audio/draw.mp3',
    },
    {
      word: 'sing',
      translation: 'петь',
      image: './assets/images/sing.jpg',
      audioSrc: './assets/audio/sing.mp3',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: './assets/images/fly.jpg',
      audioSrc: './assets/audio/fly.mp3',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: './assets/images/hug.jpg',
      audioSrc: './assets/audio/hug.mp3',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: './assets/images/jump.jpg',
      audioSrc: './assets/audio/jump.mp3',
    },
  ],
  [
    {
      word: 'yellow',
      translation: 'жёлтый',
      image: './assets/images/yellow.jpg',
      audioSrc: './assets/audio/yellow.mp3',
    },
    {
      word: 'black',
      translation: 'чёрный',
      image: './assets/images/black.jpg',
      audioSrc: './assets/audio/black.mp3',
    },
    {
      word: 'red',
      translation: 'красный',
      image: './assets/images/red.jpg',
      audioSrc: './assets/audio/red.mp3',
    },
    {
      word: 'orange',
      translation: 'оранжевый',
      image: './assets/images/orange.jpg',
      audioSrc: './assets/audio/orange.mp3',
    },
    {
      word: 'green',
      translation: 'зелёный',
      image: './assets/images/green.jpg',
      audioSrc: './assets/audio/green.mp3',
    },
    {
      word: 'purple',
      translation: 'фиотеловый',
      image: './assets/images/purple.jpg',
      audioSrc: './assets/audio/purple.mp3',
    },
    {
      word: 'blue',
      translation: 'синий',
      image: './assets/images/blue.jpg',
      audioSrc: './assets/audio/blue.mp3',
    },
    {
      word: 'brown',
      translation: 'коричневый',
      image: './assets/images/brown.jpg',
      audioSrc: './assets/audio/brown.mp3',
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: './assets/images/cat.jpg',
      audioSrc: './assets/audio/cat.mp3',
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      image: './assets/images/turtle.jpg',
      audioSrc: './assets/audio/turtle.mp3',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: './assets/images/chicken.jpg',
      audioSrc: './assets/audio/chicken.mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: './assets/images/dog.jpg',
      audioSrc: './assets/audio/dog.mp3',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: './assets/images/horse.jpg',
      audioSrc: './assets/audio/horse.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: './assets/images/pig.jpg',
      audioSrc: './assets/audio/pig.mp3',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: './assets/images/rabbit.jpg',
      audioSrc: './assets/audio/rabbit.mp3',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: './assets/images/sheep.jpg',
      audioSrc: './assets/audio/sheep.mp3',
    },
  ],
  [
    {
      word: 'tomato',
      translation: 'помидор',
      image: './assets/images/tomato.jpg',
      audioSrc: './assets/audio/tomato.mp3',
    },
    {
      word: 'corn',
      translation: 'кукуруза',
      image: './assets/images/corn.jpg',
      audioSrc: './assets/audio/corn.mp3',
    },
    {
      word: 'cabbage',
      translation: 'капуста',
      image: './assets/images/cabbage.jpg',
      audioSrc: './assets/audio/cabbage.mp3',
    },
    {
      word: 'pea',
      translation: 'горох',
      image: './assets/images/pea.jpg',
      audioSrc: './assets/audio/pea.mp3',
    },
    {
      word: 'potato',
      translation: 'картошка',
      image: './assets/images/potato.jpg',
      audioSrc: './assets/audio/potato.mp3',
    },
    {
      word: 'pumpkin',
      translation: 'тыква',
      image: './assets/images/pumpkin.jpg',
      audioSrc: './assets/audio/pumpkin.mp3',
    },
    {
      word: 'onion',
      translation: 'лук',
      image: './assets/images/onion.jpg',
      audioSrc: './assets/audio/onion.mp3',
    },
    {
      word: 'carrot',
      translation: 'морковь',
      image: './assets/images/carrot.jpg',
      audioSrc: './assets/audio/carrot.mp3',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: './assets/images/skirt.jpg',
      audioSrc: './assets/audio/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: './assets/images/pants.jpg',
      audioSrc: './assets/audio/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: './assets/images/blouse.jpg',
      audioSrc: './assets/audio/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: './assets/images/dress.jpg',
      audioSrc: './assets/audio/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: './assets/images/boot.jpg',
      audioSrc: './assets/audio/boot.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: './assets/images/shirt.jpg',
      audioSrc: './assets/audio/shirt.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: './assets/images/coat.jpg',
      audioSrc: './assets/audio/coat.mp3',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: './assets/images/shoe.jpg',
      audioSrc: './assets/audio/shoe.mp3',
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: './assets/images/sad.jpg',
      audioSrc: './assets/audio/sad.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: './assets/images/angry.jpg',
      audioSrc: './assets/audio/angry.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: './assets/images/happy.jpg',
      audioSrc: './assets/audio/happy.mp3',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: './assets/images/tired.jpg',
      audioSrc: './assets/audio/tired.mp3',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: './assets/images/surprised.jpg',
      audioSrc: './assets/audio/surprised.mp3',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: './assets/images/scared.jpg',
      audioSrc: './assets/audio/scared.mp3',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: './assets/images/smile.jpg',
      audioSrc: './assets/audio/smile.mp3',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: './assets/images/laugh.jpg',
      audioSrc: './assets/audio/laugh.mp3',
    },
  ],
  [
    {
      word: 'hamburger',
      translation: 'гамбургер',
      image: './assets/images/hamburger.jpg',
      audioSrc: './assets/audio/hamburger.mp3',
    },
    {
      word: 'ice-cream',
      translation: 'мороженое',
      image: './assets/images/ice-cream.jpg',
      audioSrc: './assets/audio/ice-cream.mp3',
    },
    {
      word: 'cheese',
      translation: 'сыр',
      image: './assets/images/cheese.jpg',
      audioSrc: './assets/audio/cheese.mp3',
    },
    {
      word: 'pizza',
      translation: 'пицца',
      image: './assets/images/pizza.jpg',
      audioSrc: './assets/audio/pizza.mp3',
    },
    {
      word: 'eggs',
      translation: 'яйца',
      image: './assets/images/eggs.jpg',
      audioSrc: './assets/audio/eggs.mp3',
    },
    {
      word: 'chocolate',
      translation: 'шоколад',
      image: './assets/images/chocolate.jpg',
      audioSrc: './assets/audio/chocolate.mp3',
    },
    {
      word: 'rice',
      translation: 'рис',
      image: './assets/images/rice.jpg',
      audioSrc: './assets/audio/rice.mp3',
    },
    {
      word: 'bread',
      translation: 'хлеб',
      image: './assets/images/bread.jpg',
      audioSrc: './assets/audio/bread.mp3',
    },
  ],
  [
    {
      word: 'grapes',
      translation: 'виноград',
      image: './assets/images/grapes.jpg',
      audioSrc: './assets/audio/grapes.mp3',
    },
    {
      word: 'apple',
      translation: 'яблоко',
      image: './assets/images/apple.jpg',
      audioSrc: './assets/audio/apple.mp3',
    },
    {
      word: 'pear',
      translation: 'груша',
      image: './assets/images/pear.jpg',
      audioSrc: './assets/audio/pear.mp3',
    },
    {
      word: 'banana',
      translation: 'банан',
      image: './assets/images/banana.jpg',
      audioSrc: './assets/audio/banana.mp3',
    },
    {
      word: 'melon',
      translation: 'дыня',
      image: './assets/images/melon.jpg',
      audioSrc: './assets/audio/melon.mp3',
    },
    {
      word: 'mango',
      translation: 'манго',
      image: './assets/images/mango.jpg',
      audioSrc: './assets/audio/mango.mp3',
    },
    {
      word: 'kiwi',
      translation: 'киви',
      image: './assets/images/kiwi.jpg',
      audioSrc: './assets/audio/kiwi.mp3',
    },
    {
      word: 'plum',
      translation: 'слива',
      image: './assets/images/plum.jpg',
      audioSrc: './assets/audio/plum.mp3',
    },
  ],
]


export default cards
